import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import CoreLayout from "@/components/layouts/core-layout";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <body className={`${poppins.className} antialiased`}>
        <CoreLayout>{children}</CoreLayout>
      </body>
    </html>
  );
}
